version: '3.8'

services:
  db:
    build:
      context: ./db
    container_name: cinema_db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/backup.sql:/docker-entrypoint-initdb.d/backup.sql
    ports:
      - "5433:5432"
    networks:
      - app-network

  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_nest_app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "4200:4200"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
